/**
 * DOCX-optimised invoice template.
 *
 * The PDF/HTML template uses flexbox layouts, absolute positioning, and
 * complex CSS classes — all of which `html-to-docx` either ignores or
 * mangles, producing the awkward two-page splits and broken bank blocks
 * seen in the v1 Word export.
 *
 * This template uses ONLY table-based layout with inline styles, which is
 * the strict subset `html-to-docx` handles reliably. The output mirrors
 * the same information the PDF carries but in a layout that survives the
 * conversion and remains editable in Word.
 */

import type { Invoice, CompanyConfig, BankAccount } from "../types";

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function formatAmount(n: number, currency: string = "¥"): string {
  return `${currency}${n.toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

function getTaxNote(invoice: Invoice): string {
  if (invoice.tax_mode === "tax_included") {
    return "上述报价含税,可开具增值税专用发票。";
  }
  const isCny = invoice.display_currency
    ? invoice.display_currency.toUpperCase() === "CNY"
    : invoice.currency === "¥";
  const surchargePercent = isCny ? 6 : 12;
  return `上述报价不含税;如需开票,可加收${surchargePercent}%费用开具增值税普通发票或专用发票。`;
}

function formatRatioPercent(fraction: number): string {
  const pct = fraction * 100;
  const rounded = Math.round(pct * 100) / 100;
  return `${Number.isInteger(rounded) ? rounded.toFixed(0) : rounded.toString()}%`;
}

/**
 * Brand label appended to the "Generated by" footer line. Keep aligned
 * with the PDF template.
 */
function brandLabel(invoice: Invoice): string {
  return invoice.template_id === "starlight"
    ? "Starlight Business Consulting"
    : "Feilong Business Service";
}

/**
 * Build the items table (single shared format for both invoice types — the
 * DOCX export is finance-facing and only ever ships consultant invoices
 * today, but final_payment items render correctly through the same shape).
 */
function buildItemsTableHtml(invoice: Invoice): string {
  const c = invoice.currency;
  const showDiscount = invoice.items.some(
    (it) => (it.discount_percent ?? 0) > 0,
  );

  const sorted = [...invoice.items].sort((a, b) => a.sort_order - b.sort_order);
  const headerCells = [
    "Service",
    "Service Period",
    "Price",
    "Qty",
    ...(showDiscount ? ["Discount(%)"] : []),
    "Total",
    "Chinese Translation",
    "Note",
  ];
  const headerRow = `
    <tr>
      ${headerCells
        .map(
          (h) =>
            `<th style="border:1px solid #888; padding:6px 8px; background:#F3F4F6; text-align:left; font-size:10pt;">${escapeHtml(
              h,
            )}</th>`,
        )
        .join("")}
    </tr>`;

  const bodyRows = sorted
    .map((item) => {
      const cells: string[] = [
        `<td style="border:1px solid #888; padding:6px 8px; font-size:10pt;">${escapeHtml(item.service)}</td>`,
        `<td style="border:1px solid #888; padding:6px 8px; font-size:10pt;">${escapeHtml(item.service_period)}</td>`,
        `<td style="border:1px solid #888; padding:6px 8px; font-size:10pt; text-align:right;">${formatAmount(item.price, c)}</td>`,
        `<td style="border:1px solid #888; padding:6px 8px; font-size:10pt; text-align:center;">${item.qty}</td>`,
      ];
      if (showDiscount) {
        cells.push(
          `<td style="border:1px solid #888; padding:6px 8px; font-size:10pt; text-align:center;">${
            (item.discount_percent ?? 0) > 0 ? `${item.discount_percent}%` : "-"
          }</td>`,
        );
      }
      cells.push(
        `<td style="border:1px solid #888; padding:6px 8px; font-size:10pt; text-align:right;">${formatAmount(item.line_total, c)}</td>`,
        `<td style="border:1px solid #888; padding:6px 8px; font-size:10pt;">${escapeHtml(item.chinese_translation ?? "")}</td>`,
        `<td style="border:1px solid #888; padding:6px 8px; font-size:10pt;">${escapeHtml(item.remark ?? "")}</td>`,
      );
      return `<tr>${cells.join("")}</tr>`;
    })
    .join("\n");

  return `
    <table style="width:100%; border-collapse:collapse; margin:8pt 0;">
      <thead>${headerRow}</thead>
      <tbody>${bodyRows}</tbody>
    </table>`;
}

/**
 * Right-aligned totals table.
 */
function buildTotalsTableHtml(invoice: Invoice): string {
  const c = invoice.currency;
  const rows: Array<[string, string, boolean]> = [];

  if (invoice.invoice_type === "final_payment") {
    rows.push(["Actual Amount (Subtotal)", formatAmount(invoice.subtotal, c), false]);
    if (typeof invoice.amount_paid_total === "number") {
      rows.push([
        "Less: Amount Paid",
        `−${formatAmount(invoice.amount_paid_total, c)}`,
        false,
      ]);
    }
    if (typeof invoice.total_deduction_amount === "number") {
      rows.push([
        "Less: Total Deduction",
        `−${formatAmount(invoice.total_deduction_amount, c)}`,
        false,
      ]);
    }
    if (typeof invoice.amount_refunded === "number") {
      rows.push([
        "Add: Amount Refunded",
        `+${formatAmount(invoice.amount_refunded, c)}`,
        false,
      ]);
    }
    rows.push([
      "Grand Total (Final Payment)",
      formatAmount(invoice.grand_total, c),
      true,
    ]);
  } else {
    rows.push(["Total", formatAmount(invoice.subtotal, c), false]);
    if (invoice.vat_rate > 0) {
      rows.push([
        `Add: VAT(${invoice.vat_rate}%)`,
        `+${formatAmount(invoice.vat_amount, c)}`,
        false,
      ]);
    }
    if ((invoice.ewt_rate ?? 0) > 0) {
      rows.push([
        `Less: EWT(${invoice.ewt_rate}%)`,
        `−${formatAmount(invoice.ewt_amount ?? 0, c)}`,
        false,
      ]);
    }
    rows.push(["Grand Total", formatAmount(invoice.grand_total, c), true]);
  }

  const trs = rows
    .map(([label, value, isGrand]) => {
      const labelStyle = `padding:4px 8px; font-size:11pt; ${
        isGrand ? "font-weight:bold; border-top:1px solid #333;" : ""
      } text-align:right;`;
      const valueStyle = `padding:4px 8px; font-size:11pt; ${
        isGrand ? "font-weight:bold; border-top:1px solid #333;" : ""
      } text-align:right; min-width:120px;`;
      return `<tr><td style="${labelStyle}">${escapeHtml(label)}</td><td style="${valueStyle}">${escapeHtml(value)}</td></tr>`;
    })
    .join("\n");

  return `
    <table style="margin:8pt 0 8pt auto; border-collapse:collapse;">
      ${trs}
    </table>`;
}

/**
 * Bank info — laid out as a single tight table so the rows can never be
 * split across pages (that was the main visual bug in the v1 export).
 */
function buildBankBlockHtml(bank: BankAccount): string {
  const row = (label: string, value: string): string => `
    <tr>
      <td style="padding:3px 12px 3px 8px; font-size:10pt; font-weight:bold; white-space:nowrap; vertical-align:top;">${escapeHtml(label)}:</td>
      <td style="padding:3px 8px; font-size:10pt;">${escapeHtml(value)}</td>
    </tr>`;
  const rows: string[] = [];
  rows.push(row("Bank Name", bank.bank_name));
  if (bank.bank_address) rows.push(row("Bank Address", bank.bank_address));
  rows.push(row("Account Name", bank.account_name));
  rows.push(row("Account Number", bank.account_number));
  if (bank.currency_label) rows.push(row("Currency", bank.currency_label));
  if (bank.swift_code) rows.push(row("Swift Code/BIC", bank.swift_code));

  // Two tables stacked: a single-row title bar above a label/value table.
  // We avoid colspan inside the label/value table (html-to-docx renders
  // colspan'd cells inconsistently) by keeping the title in its own
  // single-cell table.
  return `
    <table style="width:100%; border-collapse:collapse; margin:8pt 0 4pt 0; background:#FAFAFA;">
      <tr>
        <td style="padding:6px 10px; font-size:11pt; font-weight:bold; color:#B91C1C; border-left:3px solid #B91C1C;">${escapeHtml(bank.payment_title)}</td>
      </tr>
    </table>
    <table style="border-collapse:collapse; margin:0 0 8pt 0; padding-left:8pt;">
      ${rows.join("")}
    </table>`;
}

/**
 * Optional installment block — same bilingual sentence as the PDF, just
 * styled to survive html-to-docx (no flex / no nested CSS classes).
 */
function buildInstallmentBlockHtml(invoice: Invoice): string {
  const info = invoice.installment_info;
  if (!info) return "";
  const c = invoice.currency || "¥";
  const firstPct = formatRatioPercent(info.first_payment_ratio);
  const finalPct = formatRatioPercent(info.final_payment_ratio);
  const firstAmt = formatAmount(info.first_payment_amount, c);
  const finalAmt = formatAmount(info.final_payment_amount, c);
  const days = info.final_payment_business_days;
  const zhText = `分期付款： 首款：服务费的${firstPct}，即金额${firstAmt}，于服务启动之前支付； 尾款：服务费的${finalPct}，即金额${finalAmt}，于服务完成之后的${days}个工作日内支付。`;
  const enText = `Installment Payment: First payment: ${firstPct} of the service fee, i.e., ${firstAmt}, payable before the service commences. Final payment: ${finalPct} of the service fee, i.e., ${finalAmt}, payable within ${days} business days after the service is completed.`;
  return `
    <table style="width:100%; border-collapse:collapse; margin:6pt 0; background:#FFF9E6;">
      <tr><td style="padding:8pt 10pt; font-size:10pt; border-left:3px solid #D97706;">
        <div style="margin-bottom:4pt;">${escapeHtml(zhText)}</div>
        <div style="color:#4B5563;">${escapeHtml(enText)}</div>
      </td></tr>
    </table>`;
}

/**
 * Render the consultant/final-payment invoice as DOCX-friendly HTML.
 *
 * Layout decisions
 * - Single-column flow (no flexbox, no floats).
 * - Header: company name (large), then address lines and email.
 * - "BILL TO / INVOICE / DATE" stacked vertically — three lines, each with
 *   bold label + value. A horizontal layout via table caused Word to
 *   reflow into multiple columns on narrow margins.
 * - Items table: borders on every cell so finance can edit each cell.
 * - Totals table is right-aligned, with the Grand Total row bolded.
 * - Bank info uses one table to keep rows visually grouped.
 * - "Generated by …" rendered at the end as a single italic paragraph.
 */
export function renderInvoiceDocxHtml(
  invoice: Invoice,
  config: CompanyConfig,
  bankAccount: BankAccount,
): string {
  const bill = [invoice.company_name, invoice.bill_to]
    .map((v) => (v ?? "").trim())
    .filter((v, i, a) => v && a.indexOf(v) === i);

  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8" />
  <title>Invoice ${escapeHtml(invoice.invoice_no)}</title>
</head>
<body style="font-family: 'PingFang SC','Microsoft YaHei','Helvetica Neue',Arial,sans-serif; color:#1F2937; font-size:11pt;">

  <!-- Header: company info -->
  <table style="width:100%; border-collapse:collapse; margin-bottom:8pt;">
    <tr>
      <td style="padding:0; font-size:14pt; font-weight:bold;">${escapeHtml(config.name)}</td>
    </tr>
    <tr>
      <td style="padding:2pt 0; font-size:10pt; color:#4B5563;">${escapeHtml(config.address_line1)}</td>
    </tr>
    <tr>
      <td style="padding:0; font-size:10pt; color:#4B5563;">${escapeHtml(config.address_line2)}</td>
    </tr>
    ${
      config.address_line3
        ? `<tr><td style="padding:0; font-size:10pt; color:#4B5563;">${escapeHtml(config.address_line3)}</td></tr>`
        : ""
    }
    <tr>
      <td style="padding:2pt 0; font-size:10pt; color:#4B5563;">${escapeHtml(config.email)}</td>
    </tr>
  </table>

  <hr style="border:none; border-top:1px solid #D1D5DB; margin:8pt 0;" />

  <!-- Bill To + Invoice + Date stacked -->
  <table style="width:100%; border-collapse:collapse; margin:6pt 0 10pt 0;">
    <tr>
      <td style="padding:2pt 0; font-size:10pt; font-weight:bold; width:100pt; vertical-align:top;">BILL TO:</td>
      <td style="padding:2pt 0; font-size:11pt;">${bill.map((v) => escapeHtml(v)).join("<br/>")}</td>
    </tr>
    <tr>
      <td style="padding:2pt 0; font-size:10pt; font-weight:bold; width:100pt;">INVOICE:</td>
      <td style="padding:2pt 0; font-size:11pt;">${escapeHtml(invoice.invoice_no)}</td>
    </tr>
    <tr>
      <td style="padding:2pt 0; font-size:10pt; font-weight:bold; width:100pt;">DATE:</td>
      <td style="padding:2pt 0; font-size:11pt;">${escapeHtml(invoice.invoice_date)}</td>
    </tr>
  </table>

  <!-- Items table -->
  ${buildItemsTableHtml(invoice)}

  <!-- Totals -->
  ${buildTotalsTableHtml(invoice)}

  <!-- Optional installment block (per spec req 4) -->
  ${buildInstallmentBlockHtml(invoice)}

  <!-- Notes -->
  <p style="margin:6pt 0 2pt 0; font-size:10pt; font-weight:bold;">Notes:</p>
  <p style="margin:0 0 10pt 0; font-size:10pt;">${escapeHtml(getTaxNote(invoice))}</p>

  <!-- Bank info block -->
  ${buildBankBlockHtml(bankAccount)}

  <!-- Generated-by footer -->
  <p style="margin:14pt 0 0 0; font-size:9pt; color:#9CA3AF; text-align:center;">
    Generated by ${escapeHtml(brandLabel(invoice))} · ${escapeHtml(invoice.invoice_no)} · ${escapeHtml(invoice.invoice_date)}
  </p>

</body>
</html>`;
}
